name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm install
      
      - name: Determine playwright version from package.json
        id: get_playwright_version
        run: |
          playwright_version=$(jq -r '.devDependencies["playwright-core"]' package.json | sed 's/\^//g')
          echo "Playwright version: $playwright_version"
          echo "playwright_version=$playwright_version" >> $GITHUB_OUTPUT
      
      - run: npx playwright@${{ steps.get_playwright_version.outputs.playwright_version }} install --with-deps chromium
      
      - run: npm run lint
      
      - run: npm test
